# https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
name: Publish to repository
on:
  push:
    paths:
      - 'libraries_version.txt'
    branches:
      - develop
jobs:
  windows-upload:
    runs-on: windows-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Disable TCP-UDP offload
        run: Disable-NetAdapterChecksumOffload -Name * -TcpIPv4 -UdpIPv4 -TcpIPv6 -UdpIPv6
        shell: pwsh
      - name: Upload Windows x64 bits artifacts
        run: ./gradlew --scan publishMingwX64PublicationToBintrayRepository
        shell: bash
  macos-upload:
    runs-on: macos-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Disable TCP-UDP offload
        run: |
          sudo sysctl -w net.link.generic.system.hwcksum_tx=0
          sudo sysctl -w net.link.generic.system.hwcksum_rx=0
      - name: Upload all artifacts macOS can build
        run: ./gradlew --scan publishAllPublicationsToBintrayRepository
  windows-checking:
    runs-on: windows-latest
    needs: [windows-upload, macos-upload]
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Disable TCP-UDP offload
        run: Disable-NetAdapterChecksumOffload -Name * -TcpIPv4 -UdpIPv4 -TcpIPv6 -UdpIPv6
        shell: pwsh
      - name: Check Windows build with latest artifacts
        run: ./gradlew --scan -Psplitties.bintray.check=true :tools:publication-checker:build
        shell: bash
  macos-checking:
    runs-on: macos-latest
    needs: [windows-upload, macos-upload]
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Disable TCP-UDP offload
        run: |
          sudo sysctl -w net.link.generic.system.hwcksum_tx=0
          sudo sysctl -w net.link.generic.system.hwcksum_rx=0
      - name: Check macOS build with latest artifacts
        run: ./gradlew --scan -Psplitties.bintray.check=true :tools:publication-checker:build
  linux-checking-and-publish:
    runs-on: ubuntu-latest
    needs: [macos-checking, windows-checking]
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Disable TCP-UDP offload
        run: sudo ethtool -K eth0 tx off rx off
      - name: Check Linux build with latest artifacts
        run: ./gradlew --scan -Psplitties.bintray.check=true :tools:publication-checker:build
      - name: Publish all uploaded artifacts for this version
        run: ./gradlew --scan -Psplitties.bintray.check=true publishBintrayRelease
env:
  GRADLE_OPTS: -Dorg.gradle.parallel=true -Dkotlin.incremental=false -Dorg.gradle.project.kotlin.incremental.multiplatform=false -Dorg.gradle.project.kotlin.native.disableCompilerDaemon=true -Dorg.gradle.jvmargs="-Xmx3g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
  ORG_GRADLE_PROJECT_bintray_api_key: ${{ secrets.BINTRAY_API_KEY }}
